name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Sandervanteinde.AdventOfCode2021
      
    - name: Build
      run: dotnet build Sandervanteinde.AdventOfCode2021 -c Release
      
    - name: Publish
      run: dotnet publish Sandervanteinde.AdventOfCode2021 --no-restore --no-restore --output ${GITHUB_WORKSPACE}/docs
      
    - name: Commit
      run: |
        - mv ${GITHUB_WORKSPACE}/docs/wwwroot ${GITHUB_WORKSPACE}/docs
        - rm ${GITHUB_WORKSPACE}/docs/web.config
        - git add *
        - git commit -m "Automatically create page"
        - git push
    
